SELECT * FROM "TB_AI_NVR_DASH_BOARD_COUNT";

SELECT user_id, user_pw, user_name
		FROM TB_AI_NVR_DASH_BOARD_USER
		WHERE user_id = 'admin';
		
	

SELECT COUNT(*) FROM TB_AI_NVR_DASH_BOARD_USER
WHERE USER_ID = 'admin'
AND CAST(DECRYPTBYPASSPHRASE((SELECT site_code FROM TB_SERVER_RECORD WHERE type = 34), enc_user_pw) AS NVARCHAR(2000)) = 'admin';



EXEC SP_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY '20231106', '20231106', 0;


EXEC SP_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY_EVERY_HOUR '2023110300', '2023110399', 0;


EXEC SP_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY_BY_CAMERA '2023110600', '2023110699', 0;

SELECT
FACE_YOUNGMALE AS YOUNG_MALE    -- 미성년_남자
, FACE_YOUNGFEMALE AS YOUNG_FEMALE  -- 미성년 여자
, FACE_ADULTMALE AS ADULT_MALE   -- 성인_남자
, FACE_ADULTFEMALE AS ADULT_FEMALE  -- 성인_여자
, FACE_MIDDLEMALE AS MIDDLE_MALE   -- 중년_남자
, FACE_MIDDLEFEMALE AS MIDDLE_FEMALE -- 중년_여자
, FACE_SENIORMALE AS SENIOR_MALE   -- 노년_남자
, FACE_SENIORFEMALE AS SENIOR_FEMALE -- 노년_여자
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = '20231115';


SELECT
*
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = '20231123';

--사람
SELECT
  FACE_YOUNGMALE AS YOUNG_MALE,
  FACE_YOUNGFEMALE AS YOUNG_FEMALE,
  FACE_ADULTMALE AS ADULT_MALE,
  FACE_ADULTFEMALE AS ADULT_FEMALE,
  FACE_MIDDLEMALE AS MIDDLE_MALE,
  FACE_MIDDLEFEMALE AS MIDDLE_FEMALE,
  FACE_SENIORMALE AS SENIOR_MALE,
  FACE_SENIORFEMALE AS SENIOR_FEMALE,
  OCCU_DATE
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

--사람 누적 합계 구하기
SELECT
	SUM(FACE_YOUNGMALE + FACE_YOUNGFEMALE + FACE_ADULTMALE + FACE_ADULTFEMALE + FACE_MIDDLEMALE + FACE_MIDDLEFEMALE + FACE_SENIORMALE + FACE_SENIORFEMALE)
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT ISNULL(
           SUM(FACE_YOUNGMALE + FACE_YOUNGFEMALE + FACE_ADULTMALE + FACE_ADULTFEMALE + FACE_MIDDLEMALE + FACE_MIDDLEFEMALE + FACE_SENIORMALE + FACE_SENIORFEMALE),
           0
       ) AS TotalSum
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);


SELECT COALESCE(PERSON, 0)
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = 
CONVERT(varchar, GETDATE(), 112);


SELECT COALESCE(SUM(PERSON),0)             
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT
WHERE SUBSTRING(OCCU_TIME, 1, 8) = CONVERT(varchar, GETDATE(), 112);




SELECT CONVERT(varchar, DATEADD(DAY, 1, GETDATE()), 112) AS Tomorrow;
SELECT CONVERT(varchar, DATE(DAY, 1, GETDATE()), 112) AS Today;




SELECT
*
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
  *
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, DATEADD(DAY, 1, GETDATE()), 112);



-- 시간대별 현황
SELECT
SUBSTRING(OCCU_TIME, 9, 2)     
, PERSON             
, VEHICLE             
, FACE                   
, LPR                     
, INV_CNT              
, LOT_CNT              
, CNT_CNT             
, FAL_CNT           C43    
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT
WHERE SUBSTRING(OCCU_TIME, 1, 8) = CONVERT(varchar, GETDATE(), 112)
ORDER BY OCCU_TIME;

--마스크 미착용자 성별/연령 비교
SELECT
FACE_NOMASKMALEYOUNG         -- 마스크미착용_남자_미성년
, FACE_NOMASKMALEADULT         -- 마스크미착용_남자_성인
, FACE_NOMASKMALEMIDDLE       -- 마스크미착용_남자_중년
, FACE_NOMASKMALESENIOR        -- 마스크미착용_남자_노년
, FACE_NOMASKFEMALEYOUNG     -- 마스크미착용_여자_미성년
, FACE_NOMASKFEMALEADULT      -- 마스크미착용_여자_성인
, FACE_NOMASKFEMALEMIDDLE     -- 마스크미착용_여자_중년
, FACE_NOMASKFEMALESENIOR     -- 마스크미착용_여자_노년
, OCCU_DATE
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);



SELECT
TOP 10
CNT.CAMERA_NAME   
, SUM(CNT.TOT_CNT)                       -- 카메라명
, SUM(CNT.PERSON)   AS PERSON     -- 사람
, SUM(CNT.VEHICLE)  AS VEHICLE     -- 차량
, SUM(CNT.FACE)   AS FACE             -- 얼굴
, SUM(CNT.LPR)    AS LPR                -- 차량번호판
, SUM(CNT.INV_CNT)  AS INV_CNT    -- 침입
, SUM(CNT.LOT_CNT)  AS LOT_CNT    -- 배회
, SUM(CNT.CNT_CNT)  AS CNT_CNT   -- 카운팅
, SUM(CNT.FAL_CNT)  AS FAL_CNT     -- 쓰러짐
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT CNT
WHERE SUBSTRING(CNT.OCCU_TIME, 1, 8) = CONVERT(varchar, GETDATE(), 112)
GROUP BY CNT.CAMERA_NAME
ORDER BY SUM(CNT.TOT_CNT);

-- 사람 최다검지 카메라
SELECT
			TOP 10
			CNT.CAMERA_NAME   
			, SUM(CNT.PERSON)   AS personCount     
			, SUM(CNT.VEHICLE)  AS vehicleCount     
			, SUM(CNT.FACE)   AS faceCount             
			, SUM(CNT.LPR)    AS lprCount               
			, SUM(CNT.INV_CNT)  AS invCntCount   
			, SUM(CNT.LOT_CNT)  AS lotCntCount   
			, SUM(CNT.CNT_CNT)  AS cntCntCount   
			, SUM(CNT.FAL_CNT)  AS falCntCont     
		FROM "TB_AI_NVR_DASH_BOARD_DAILY_COUNT" CNT
		WHERE SUBSTRING(CNT.OCCU_TIME, 1, 8) = CONVERT(varchar, GETDATE(), 112)
		GROUP BY CNT.CAMERA_NAME
		ORDER BY SUM(CNT.TOT_CNT);
	
	--차량 최다검지카메라
	SELECT TOP 10
    CNT.CAMERA_NAME,
    SUM(CNT.TOT_CNT) AS total_count,
    SUM(CNT.VEHICLE_CAR) AS carCount,
    SUM(CNT.VEHICLE_BUS) AS busCount,
    SUM(CNT.VEHICLE_TRUCK) AS truckCount,
    SUM(CNT.VEHICLE_MOTORCYCLE) AS motocycleCount,
    SUM(CNT.VEHICLE_BICYCLE) AS bicycleCount
FROM "TB_AI_NVR_DASH_BOARD_DAILY_COUNT" CNT
WHERE SUBSTRING(CNT.OCCU_TIME, 1, 8) = CONVERT(varchar, GETDATE(), 112)
GROUP BY CNT.CAMERA_NAME
ORDER BY SUM(CNT.TOT_CNT) DESC;



--차량 막대차트
SELECT
	VEHICLE_CAR 
	, VEHICLE_BUS 
	, VEHICLE_TRUCK 
	, VEHICLE_MOTORCYCLE 
	, VEHICLE_BICYCLE 
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

-- 차량 누적 수 
SELECT 
    ISNULL(
        SUM(CNT.VEHICLE_CAR + CNT.VEHICLE_BUS + CNT.VEHICLE_TRUCK + CNT.VEHICLE_MOTORCYCLE + CNT.VEHICLE_BICYCLE),
        0
    ) AS TotalSum
FROM "TB_AI_NVR_DASH_BOARD_DAILY_COUNT" CNT
WHERE SUBSTRING(CNT.OCCU_TIME, 1, 8) = CONVERT(varchar, GETDATE(), 112);

-- 이벤트 발생 비율
SELECT
	INV_CNT
	, LOT_CNT
	, CNT_CNT 
	, FAL_CNT   
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);







-- 마스크를 착용한 남자의 비율 계산
SELECT
    COALESCE(
        CASE
            WHEN COUNT(*) > 0 THEN
                (SUM(CASE WHEN FACE_MALE > 0 THEN FACE_MASKMALE ELSE 0 END) * 100.0 / SUM(FACE_MALE))
            ELSE
                0
        END,
        0
    ) AS mask_wearing_male_ratio
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);






-- 마스크를 착용한 여자의 비율 계산
SELECT
    CASE
        WHEN SUM(FACE_FEMALE) > 0 THEN
            (SUM(CASE WHEN FACE_FEMALE > 0 THEN FACE_MASKFEMALE ELSE 0 END) * 100.0 / SUM(FACE_FEMALE))
        ELSE
            0
    END AS mask_wearing_female_ratio
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);



	
	

-- 오늘 합산

SELECT
	PERSON, VEHICLE, FACE, LPR, INV_CNT, LOT_CNT, CNT_CNT, FAL_CNT  
		FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
		WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);
	
	
	



-- 전일대비
WITH Today AS (
    SELECT
	PERSON, VEHICLE, FACE, LPR, INV_CNT, LOT_CNT, CNT_CNT, FAL_CNT  
		FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
		WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112)
),
Yesterday AS (
    SELECT
        PERSON, VEHICLE, FACE, LPR, INV_CNT, LOT_CNT, CNT_CNT, FAL_CNT  
		FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
		WHERE OCCU_DATE = CONVERT(varchar, DATEADD(day, -1, GETDATE()), 112)
)
SELECT
    t.PERSON - y.PERSON AS personCount_DIFF,
    t.VEHICLE - y.VEHICLE AS vehicleCount_DIFF,
    t.FACE - y.FACE AS faceCount_DIFF,
    t.LPR - y.LPR AS lprCount_DIFF,
    t.INV_CNT - y.INV_CNT AS invCntCount_DIFF,
    t.LOT_CNT - y.LOT_CNT AS lotCntCount_DIFF,
    t.CNT_CNT - y.CNT_CNT AS cntCntCount_DIFF,
    t.FAL_CNT - y.FAL_CNT AS falCntCount_DIFF
FROM Today t
JOIN Yesterday y ON 1 = 1;





--사람페이지 성별 도넛차트

SELECT
    COALESCE(PERSON_FEMALE, 0) AS personFemale,
    COALESCE(PERSON_MALE, 0) AS personMale
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);




-- 악세사리
SELECT
	PERSON_HATMALE 
	, PERSON_BAGMALE 
	, PERSON_HATFEMALE 
	, PERSON_BAGFEMALE 
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);



--의류선호도--


-- 상의 색상 --
-- 남성 상의 색 분류
SELECT
  SUM(PERSON_TOPWEARBLACKMALE + PERSON_TOPWEARGRAYMALE + PERSON_TOPWEARWHITEMALE 
    + PERSON_TOPWEARREDMALE + PERSON_TOPWEARORANGEMALE + PERSON_TOPWEARYELLOWMALE
    + PERSON_TOPWEARGREENMALE + PERSON_TOPWEARBLUEMALE + PERSON_TOPWEARPURPLEMALE) AS TOPWEARMAN
 FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
   SUM(PERSON_TOPWEARBLACKMALE+PERSON_TOPWEARGRAYMALE+PERSON_TOPWEARWHITEMALE) 
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
  SUM(PERSON_TOPWEARREDMALE+PERSON_TOPWEARORANGEMALE+PERSON_TOPWEARYELLOWMALE) 
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
  SUM(PERSON_TOPWEARGREENMALE+PERSON_TOPWEARBLUEMALE+PERSON_TOPWEARPURPLEMALE) 
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

-- 무채색 상의를 입은 남성
SELECT
    CASE
        WHEN SUM(PERSON_TOPWEARBLACKMALE + PERSON_TOPWEARGRAYMALE + PERSON_TOPWEARWHITEMALE 
            + PERSON_TOPWEARREDMALE + PERSON_TOPWEARORANGEMALE + PERSON_TOPWEARYELLOWMALE
            + PERSON_TOPWEARGREENMALE + PERSON_TOPWEARBLUEMALE + PERSON_TOPWEARPURPLEMALE) > 0 THEN
            (SUM(CASE WHEN PERSON_TOPWEARBLACKMALE + PERSON_TOPWEARGRAYMALE + PERSON_TOPWEARWHITEMALE > 0 
                THEN PERSON_TOPWEARBLACKMALE + PERSON_TOPWEARGRAYMALE + PERSON_TOPWEARWHITEMALE ELSE 0 END) * 100.0 /
                SUM(PERSON_TOPWEARBLACKMALE + PERSON_TOPWEARGRAYMALE + PERSON_TOPWEARWHITEMALE 
                    + PERSON_TOPWEARREDMALE + PERSON_TOPWEARORANGEMALE + PERSON_TOPWEARYELLOWMALE
                    + PERSON_TOPWEARGREENMALE + PERSON_TOPWEARBLUEMALE + PERSON_TOPWEARPURPLEMALE))
        ELSE
            0
    END AS MONOCHROMATIC_PERCENTAGE_TOPWEARMAN
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

-- 난색 상의를 입은 남성
SELECT
    CASE
        WHEN SUM(PERSON_TOPWEARBLACKMALE + PERSON_TOPWEARGRAYMALE + PERSON_TOPWEARWHITEMALE 
            + PERSON_TOPWEARREDMALE + PERSON_TOPWEARORANGEMALE + PERSON_TOPWEARYELLOWMALE
            + PERSON_TOPWEARGREENMALE + PERSON_TOPWEARBLUEMALE + PERSON_TOPWEARPURPLEMALE) > 0 THEN
            (SUM(CASE WHEN PERSON_TOPWEARREDMALE + PERSON_TOPWEARORANGEMALE + PERSON_TOPWEARYELLOWMALE > 0 
                THEN PERSON_TOPWEARREDMALE + PERSON_TOPWEARORANGEMALE + PERSON_TOPWEARYELLOWMALE ELSE 0 END) * 100.0 /
                SUM(PERSON_TOPWEARBLACKMALE + PERSON_TOPWEARGRAYMALE + PERSON_TOPWEARWHITEMALE 
                    + PERSON_TOPWEARREDMALE + PERSON_TOPWEARORANGEMALE + PERSON_TOPWEARYELLOWMALE
                    + PERSON_TOPWEARGREENMALE + PERSON_TOPWEARBLUEMALE + PERSON_TOPWEARPURPLEMALE))
        ELSE
            0
    END AS POLYCHROMATIC_PERCENTAGE_TOPWEARMAN
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

-- 한색 상의를 입은 남성
SELECT
    CASE
        WHEN SUM(PERSON_TOPWEARBLACKMALE + PERSON_TOPWEARGRAYMALE + PERSON_TOPWEARWHITEMALE 
            + PERSON_TOPWEARREDMALE + PERSON_TOPWEARORANGEMALE + PERSON_TOPWEARYELLOWMALE
            + PERSON_TOPWEARGREENMALE + PERSON_TOPWEARBLUEMALE + PERSON_TOPWEARPURPLEMALE) > 0 THEN
            (SUM(CASE WHEN PERSON_TOPWEARGREENMALE+PERSON_TOPWEARBLUEMALE+PERSON_TOPWEARPURPLEMALE > 0 
                THEN PERSON_TOPWEARGREENMALE+PERSON_TOPWEARBLUEMALE+PERSON_TOPWEARPURPLEMALE ELSE 0 END) * 100.0 /
                SUM(PERSON_TOPWEARBLACKMALE + PERSON_TOPWEARGRAYMALE + PERSON_TOPWEARWHITEMALE 
                    + PERSON_TOPWEARREDMALE + PERSON_TOPWEARORANGEMALE + PERSON_TOPWEARYELLOWMALE
                    + PERSON_TOPWEARGREENMALE + PERSON_TOPWEARBLUEMALE + PERSON_TOPWEARPURPLEMALE))
        ELSE
            0
    END AS HUES_PERCENTAGE_TOPWEARMAN
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);





-- 여성 상의 색 분류
SELECT
  SUM(PERSON_TOPWEARBLACKFEMALE + PERSON_TOPWEARGRAYFEMALE + PERSON_TOPWEARWHITEFEMALE 
    + PERSON_TOPWEARREDFEMALE + PERSON_TOPWEARORANGEFEMALE + PERSON_TOPWEARYELLOWFEMALE
    + PERSON_TOPWEARGREENFEMALE + PERSON_TOPWEARBLUEFEMALE + PERSON_TOPWEARPURPLEFEMALE) AS TOPWEARWOMAN
 FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
   SUM(PERSON_TOPWEARBLACKFEMALE+PERSON_TOPWEARGRAYFEMALE+PERSON_TOPWEARWHITEFEMALE) 
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
  SUM(PERSON_TOPWEARREDFEMALE+PERSON_TOPWEARORANGEFEMALE+PERSON_TOPWEARYELLOWFEMALE) 
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
  SUM(PERSON_TOPWEARGREENFEMALE+PERSON_TOPWEARBLUEFEMALE+PERSON_TOPWEARPURPLEFEMALE) 
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);



-- 무채색 상의를 입은 여성
SELECT
    CASE
        WHEN SUM(PERSON_TOPWEARBLACKFEMALE + PERSON_TOPWEARGRAYFEMALE + PERSON_TOPWEARWHITEFEMALE 
            + PERSON_TOPWEARREDFEMALE + PERSON_TOPWEARORANGEFEMALE + PERSON_TOPWEARYELLOWFEMALE
            + PERSON_TOPWEARGREENFEMALE + PERSON_TOPWEARBLUEFEMALE + PERSON_TOPWEARPURPLEFEMALE) > 0 THEN
            (SUM(CASE WHEN PERSON_TOPWEARBLACKFEMALE + PERSON_TOPWEARGRAYFEMALE + PERSON_TOPWEARWHITEFEMALE > 0 
                THEN PERSON_TOPWEARBLACKFEMALE + PERSON_TOPWEARGRAYFEMALE + PERSON_TOPWEARWHITEFEMALE ELSE 0 END) * 100.0 /
                SUM(PERSON_TOPWEARBLACKFEMALE + PERSON_TOPWEARGRAYFEMALE + PERSON_TOPWEARWHITEFEMALE 
                    + PERSON_TOPWEARREDFEMALE + PERSON_TOPWEARORANGEFEMALE + PERSON_TOPWEARYELLOWFEMALE
                    + PERSON_TOPWEARGREENFEMALE + PERSON_TOPWEARBLUEFEMALE + PERSON_TOPWEARPURPLEFEMALE))
        ELSE
            0
    END AS MONOCHROMATIC_PERCENTAGE_TOPWEARWOMAN
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

-- 난색 상의를 입은 여성
SELECT
    CASE
        WHEN SUM(PERSON_TOPWEARBLACKFEMALE + PERSON_TOPWEARGRAYFEMALE + PERSON_TOPWEARWHITEFEMALE 
            + PERSON_TOPWEARREDFEMALE + PERSON_TOPWEARORANGEFEMALE + PERSON_TOPWEARYELLOWFEMALE
            + PERSON_TOPWEARGREENFEMALE + PERSON_TOPWEARBLUEFEMALE + PERSON_TOPWEARPURPLEFEMALE) > 0 THEN
            (SUM(CASE WHEN PERSON_TOPWEARREDFEMALE + PERSON_TOPWEARORANGEFEMALE + PERSON_TOPWEARYELLOWFEMALE > 0 
                THEN PERSON_TOPWEARREDFEMALE + PERSON_TOPWEARORANGEFEMALE + PERSON_TOPWEARYELLOWFEMALE ELSE 0 END) * 100.0 /
                SUM(PERSON_TOPWEARBLACKFEMALE + PERSON_TOPWEARGRAYFEMALE + PERSON_TOPWEARWHITEFEMALE 
                    + PERSON_TOPWEARREDFEMALE + PERSON_TOPWEARORANGEFEMALE + PERSON_TOPWEARYELLOWFEMALE
                    + PERSON_TOPWEARGREENFEMALE + PERSON_TOPWEARBLUEFEMALE + PERSON_TOPWEARPURPLEFEMALE))
        ELSE
            0
    END AS POLYCHROMATIC_PERCENTAGE_TOPWEARWOMAN
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

-- 한색 상의를 입은 여성
SELECT
    CASE
        WHEN SUM(PERSON_TOPWEARBLACKFEMALE + PERSON_TOPWEARGRAYFEMALE + PERSON_TOPWEARWHITEFEMALE 
            + PERSON_TOPWEARREDFEMALE + PERSON_TOPWEARORANGEFEMALE + PERSON_TOPWEARYELLOWFEMALE
            + PERSON_TOPWEARGREENFEMALE + PERSON_TOPWEARBLUEFEMALE + PERSON_TOPWEARPURPLEFEMALE) > 0 THEN
            (SUM(CASE WHEN PERSON_TOPWEARGREENFEMALE+PERSON_TOPWEARBLUEFEMALE+PERSON_TOPWEARPURPLEFEMALE > 0 
                THEN PERSON_TOPWEARGREENFEMALE+PERSON_TOPWEARBLUEFEMALE+PERSON_TOPWEARPURPLEFEMALE ELSE 0 END) * 100.0 /
                SUM(PERSON_TOPWEARBLACKFEMALE + PERSON_TOPWEARGRAYFEMALE + PERSON_TOPWEARWHITEFEMALE 
                    + PERSON_TOPWEARREDFEMALE + PERSON_TOPWEARORANGEFEMALE + PERSON_TOPWEARYELLOWFEMALE
                    + PERSON_TOPWEARGREENFEMALE + PERSON_TOPWEARBLUEFEMALE + PERSON_TOPWEARPURPLEFEMALE))
        ELSE
            0
    END AS HUES_PERCENTAGE_TOPWEARWOMAN
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);





-- 하의 색상 --
-- 남성 하의 색 분류 --

SELECT
  SUM(PERSON_BOTTOMWEARBLACKMALE + PERSON_BOTTOMWEARGRAYMALE + PERSON_BOTTOMWEARWHITEMALE 
    + PERSON_BOTTOMWEARREDMALE + PERSON_BOTTOMWEARORANGEMALE + PERSON_BOTTOMWEARYELLOWMALE
    + PERSON_BOTTOMWEARGREENMALE + PERSON_BOTTOMWEARBLUEMALE + PERSON_BOTTOMWEARPURPLEMALE) AS BOTTOMWEARMAN
 FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
   SUM(PERSON_BOTTOMWEARBLACKMALE+PERSON_BOTTOMWEARGRAYMALE+PERSON_BOTTOMWEARWHITEMALE) 
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
  SUM(PERSON_BOTTOMWEARREDMALE+PERSON_BOTTOMWEARORANGEMALE+PERSON_BOTTOMWEARYELLOWMALE) 
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
  SUM(PERSON_BOTTOMWEARGREENMALE+PERSON_BOTTOMWEARBLUEMALE+PERSON_BOTTOMWEARPURPLEMALE) 
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

-- 무채색 하의를 입은 남성
SELECT
    CASE
        WHEN SUM(PERSON_BOTTOMWEARBLACKMALE + PERSON_BOTTOMWEARGRAYMALE + PERSON_BOTTOMWEARWHITEMALE 
            + PERSON_BOTTOMWEARREDMALE + PERSON_BOTTOMWEARORANGEMALE + PERSON_BOTTOMWEARYELLOWMALE
            + PERSON_BOTTOMWEARGREENMALE + PERSON_BOTTOMWEARBLUEMALE + PERSON_BOTTOMWEARPURPLEMALE) > 0 THEN
            (SUM(CASE WHEN PERSON_BOTTOMWEARBLACKMALE + PERSON_BOTTOMWEARGRAYMALE + PERSON_BOTTOMWEARWHITEMALE > 0 
                THEN PERSON_BOTTOMWEARBLACKMALE + PERSON_BOTTOMWEARGRAYMALE + PERSON_BOTTOMWEARWHITEMALE ELSE 0 END) * 100.0 /
                SUM(PERSON_BOTTOMWEARBLACKMALE + PERSON_BOTTOMWEARGRAYMALE + PERSON_BOTTOMWEARWHITEMALE 
                    + PERSON_BOTTOMWEARREDMALE + PERSON_BOTTOMWEARORANGEMALE + PERSON_BOTTOMWEARYELLOWMALE
                    + PERSON_BOTTOMWEARGREENMALE + PERSON_BOTTOMWEARBLUEMALE + PERSON_BOTTOMWEARPURPLEMALE))
        ELSE
            0
    END AS MONOCHROMATIC_PERCENTAGE_BOTTOMWEARMAN
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

-- 난색 하의를 입은 남성
SELECT
    CASE
        WHEN SUM(PERSON_BOTTOMWEARBLACKMALE + PERSON_BOTTOMWEARGRAYMALE + PERSON_BOTTOMWEARWHITEMALE 
            + PERSON_BOTTOMWEARREDMALE + PERSON_BOTTOMWEARORANGEMALE + PERSON_BOTTOMWEARYELLOWMALE
            + PERSON_BOTTOMWEARGREENMALE + PERSON_BOTTOMWEARBLUEMALE + PERSON_BOTTOMWEARPURPLEMALE) > 0 THEN
            (SUM(CASE WHEN PERSON_BOTTOMWEARREDMALE + PERSON_BOTTOMWEARORANGEMALE + PERSON_BOTTOMWEARYELLOWMALE > 0 
                THEN PERSON_BOTTOMWEARREDMALE + PERSON_BOTTOMWEARORANGEMALE + PERSON_BOTTOMWEARYELLOWMALE ELSE 0 END) * 100.0 /
                SUM(PERSON_BOTTOMWEARBLACKMALE + PERSON_BOTTOMWEARGRAYMALE + PERSON_TOPWEARWHITEMALE 
                    + PERSON_BOTTOMWEARREDMALE + PERSON_BOTTOMWEARORANGEMALE + PERSON_TOPWEARYELLOWMALE
                    + PERSON_BOTTOMWEARGREENMALE + PERSON_BOTTOMWEARBLUEMALE + PERSON_TOPWEARPURPLEMALE))
        ELSE
            0
    END AS POLYCHROMATIC_PERCENTAGE_BOTTOMWEARMAN
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

-- 한색 하의를 입은 남성
SELECT
    CASE
        WHEN SUM(PERSON_BOTTOMWEARBLACKMALE + PERSON_BOTTOMWEARGRAYMALE + PERSON_BOTTOMWEARWHITEMALE 
            + PERSON_BOTTOMWEARREDMALE + PERSON_BOTTOMWEARORANGEMALE + PERSON_BOTTOMWEARYELLOWMALE
            + PERSON_BOTTOMWEARGREENMALE + PERSON_BOTTOMWEARBLUEMALE + PERSON_BOTTOMWEARPURPLEMALE) > 0 THEN
            (SUM(CASE WHEN PERSON_BOTTOMWEARGREENMALE+PERSON_BOTTOMWEARBLUEMALE+PERSON_BOTTOMWEARPURPLEMALE > 0 
                THEN PERSON_BOTTOMWEARGREENMALE+PERSON_BOTTOMWEARBLUEMALE+PERSON_BOTTOMWEARPURPLEMALE ELSE 0 END) * 100.0 /
                SUM(PERSON_BOTTOMWEARBLACKMALE + PERSON_BOTTOMWEARGRAYMALE + PERSON_BOTTOMWEARWHITEMALE 
                    + PERSON_BOTTOMWEARREDMALE + PERSON_BOTTOMWEARORANGEMALE + PERSON_BOTTOMWEARYELLOWMALE
                    + PERSON_BOTTOMWEARGREENMALE + PERSON_BOTTOMWEARBLUEMALE + PERSON_BOTTOMWEARPURPLEMALE))
        ELSE
            0
    END AS HUES_PERCENTAGE_BOTTOMWEARMAN
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);





-- 여성 하의 색 분류 --
SELECT
  SUM(PERSON_BOTTOMWEARBLACKFEMALE + PERSON_BOTTOMWEARGRAYFEMALE + PERSON_BOTTOMWEARWHITEFEMALE 
    + PERSON_BOTTOMWEARREDFEMALE + PERSON_BOTTOMWEARORANGEFEMALE + PERSON_BOTTOMWEARYELLOWFEMALE
    + PERSON_BOTTOMWEARGREENFEMALE + PERSON_BOTTOMWEARBLUEFEMALE + PERSON_BOTTOMWEARPURPLEFEMALE) AS TOPWEARWOMAN
 FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
   SUM(PERSON_BOTTOMWEARBLACKFEMALE+PERSON_BOTTOMWEARGRAYFEMALE+PERSON_BOTTOMWEARWHITEFEMALE) 
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
  SUM(PERSON_BOTTOMWEARREDFEMALE+PERSON_BOTTOMWEARORANGEFEMALE+PERSON_BOTTOMWEARYELLOWFEMALE) 
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
  SUM(PERSON_BOTTOMWEARGREENFEMALE+PERSON_BOTTOMWEARBLUEFEMALE+PERSON_BOTTOMWEARPURPLEFEMALE) 
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);



-- 무채색 상의를 입은 여성
SELECT
    CASE
        WHEN SUM(PERSON_BOTTOMWEARBLACKFEMALE + PERSON_BOTTOMWEARGRAYFEMALE + PERSON_BOTTOMWEARWHITEFEMALE 
            + PERSON_BOTTOMWEARREDFEMALE + PERSON_BOTTOMWEARORANGEFEMALE + PERSON_BOTTOMWEARYELLOWFEMALE
            + PERSON_BOTTOMWEARGREENFEMALE + PERSON_BOTTOMWEARBLUEFEMALE + PERSON_BOTTOMWEARPURPLEFEMALE) > 0 THEN
            (SUM(CASE WHEN PERSON_BOTTOMWEARBLACKFEMALE + PERSON_BOTTOMWEARGRAYFEMALE + PERSON_BOTTOMWEARWHITEFEMALE > 0 
                THEN PERSON_BOTTOMWEARBLACKFEMALE + PERSON_BOTTOMWEARGRAYFEMALE + PERSON_BOTTOMWEARWHITEFEMALE ELSE 0 END) * 100.0 /
                SUM(PERSON_BOTTOMWEARBLACKFEMALE + PERSON_BOTTOMWEARGRAYFEMALE + PERSON_BOTTOMWEARWHITEFEMALE 
                    + PERSON_BOTTOMWEARREDFEMALE + PERSON_BOTTOMWEARORANGEFEMALE + PERSON_BOTTOMWEARYELLOWFEMALE
                    + PERSON_BOTTOMWEARGREENFEMALE + PERSON_BOTTOMWEARBLUEFEMALE + PERSON_BOTTOMWEARPURPLEFEMALE))
        ELSE
            0
    END AS MONOCHROMATIC_PERCENTAGE_BOTTOMWEARWOMAN
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

-- 난색 상의를 입은 여성
SELECT
    CASE
        WHEN SUM(PERSON_BOTTOMWEARBLACKFEMALE + PERSON_BOTTOMWEARGRAYFEMALE + PERSON_BOTTOMWEARWHITEFEMALE 
            + PERSON_BOTTOMWEARREDFEMALE + PERSON_BOTTOMWEARORANGEFEMALE + PERSON_BOTTOMWEARYELLOWFEMALE
            + PERSON_BOTTOMWEARGREENFEMALE + PERSON_BOTTOMWEARBLUEFEMALE + PERSON_BOTTOMWEARPURPLEFEMALE) > 0 THEN
            (SUM(CASE WHEN PERSON_BOTTOMWEARREDFEMALE + PERSON_BOTTOMWEARORANGEFEMALE + PERSON_BOTTOMWEARYELLOWFEMALE > 0 
                THEN PERSON_BOTTOMWEARREDFEMALE + PERSON_BOTTOMWEARORANGEFEMALE + PERSON_BOTTOMWEARYELLOWFEMALE ELSE 0 END) * 100.0 /
                SUM(PERSON_BOTTOMWEARBLACKFEMALE + PERSON_BOTTOMWEARGRAYFEMALE + PERSON_BOTTOMWEARWHITEFEMALE 
                    + PERSON_BOTTOMWEARREDFEMALE + PERSON_BOTTOMWEARORANGEFEMALE + PERSON_BOTTOMWEARYELLOWFEMALE
                    + PERSON_BOTTOMWEARGREENFEMALE + PERSON_BOTTOMWEARBLUEFEMALE + PERSON_BOTTOMWEARPURPLEFEMALE))
        ELSE
            0
    END AS POLYCHROMATIC_PERCENTAGE_BOTTOMWEARWOMAN
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

-- 한색 상의를 입은 여성
SELECT
    CASE
        WHEN SUM(PERSON_BOTTOMWEARBLACKFEMALE + PERSON_BOTTOMWEARGRAYFEMALE + PERSON_BOTTOMWEARWHITEFEMALE 
            + PERSON_BOTTOMWEARREDFEMALE + PERSON_BOTTOMWEARORANGEFEMALE + PERSON_BOTTOMWEARYELLOWFEMALE
            + PERSON_BOTTOMWEARGREENFEMALE + PERSON_BOTTOMWEARBLUEFEMALE + PERSON_BOTTOMWEARPURPLEFEMALE) > 0 THEN
            (SUM(CASE WHEN PERSON_BOTTOMWEARGREENFEMALE+PERSON_BOTTOMWEARBLUEFEMALE+PERSON_BOTTOMWEARPURPLEFEMALE > 0 
                THEN PERSON_BOTTOMWEARGREENFEMALE+PERSON_BOTTOMWEARBLUEFEMALE+PERSON_BOTTOMWEARPURPLEFEMALE ELSE 0 END) * 100.0 /
                SUM(PERSON_BOTTOMWEARBLACKFEMALE + PERSON_BOTTOMWEARGRAYFEMALE + PERSON_BOTTOMWEARWHITEFEMALE 
                    + PERSON_BOTTOMWEARREDFEMALE + PERSON_BOTTOMWEARORANGEFEMALE + PERSON_BOTTOMWEARYELLOWFEMALE
                    + PERSON_BOTTOMWEARGREENFEMALE + PERSON_BOTTOMWEARBLUEFEMALE + PERSON_BOTTOMWEARPURPLEFEMALE))
        ELSE
            0
    END AS HUES_PERCENTAGE_BOTTOMWEARWOMAN
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);




-- 의복 길이 --

--남성 --
--상의
SELECT
  SUM(PERSON_TOPWEARLONGMALE + PERSON_TOPWEARSHORTMALE) AS TOPWEARMAN
 FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
  PERSON_TOPWEARLONGMALE
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
  PERSON_TOPWEARSHORTMALE
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);



-- 긴 상의를 입은 남성 비율
SELECT
    CASE
        WHEN SUM(PERSON_TOPWEARLONGMALE + PERSON_TOPWEARSHORTMALE) > 0 THEN
            (SUM(CASE WHEN PERSON_TOPWEARLONGMALE > 0 
                THEN PERSON_TOPWEARLONGMALE ELSE 0 END) * 100.0 /
                SUM(PERSON_TOPWEARLONGMALE + PERSON_TOPWEARSHORTMALE))
        ELSE
            0
    END AS LONGTOPWEARMAN
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

-- 짧은 상의를 입은 남성 비율
SELECT
    CASE
        WHEN SUM(PERSON_TOPWEARLONGMALE + PERSON_TOPWEARSHORTMALE) > 0 THEN
            (SUM(CASE WHEN PERSON_TOPWEARSHORTMALE > 0 
                THEN PERSON_TOPWEARSHORTMALE ELSE 0 END) * 100.0 /
                SUM(PERSON_TOPWEARLONGMALE + PERSON_TOPWEARSHORTMALE))
        ELSE
            0
    END AS SHORTTOPWEARMAN
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);




--하의
SELECT
  SUM(PERSON_BOTTOMWEARLONGMALE + PERSON_BOTTOMWEARSHORTMALE) AS TOPWEARMAN
 FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
  PERSON_BOTTOMWEARLONGMALE
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
  PERSON_BOTTOMWEARSHORTMALE
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

-- 긴 하의를 입은 남성
SELECT
    CASE
        WHEN SUM(PERSON_BOTTOMWEARLONGMALE + PERSON_BOTTOMWEARSHORTMALE) > 0 THEN
            (SUM(CASE WHEN PERSON_BOTTOMWEARLONGMALE > 0 
                THEN PERSON_BOTTOMWEARLONGMALE ELSE 0 END) * 100.0 /
                SUM(PERSON_BOTTOMWEARLONGMALE + PERSON_BOTTOMWEARSHORTMALE))
        ELSE
            0
    END AS LONGBOTTOMWEARMAN
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);


-- 짧은 상의를 입은 남성 비율
SELECT
    CASE
        WHEN SUM(PERSON_BOTTOMWEARLONGMALE + PERSON_BOTTOMWEARSHORTMALE) > 0 THEN
            (SUM(CASE WHEN PERSON_BOTTOMWEARSHORTMALE > 0 
                THEN PERSON_BOTTOMWEARSHORTMALE ELSE 0 END) * 100.0 /
                SUM(PERSON_BOTTOMWEARLONGMALE + PERSON_BOTTOMWEARSHORTMALE))
        ELSE
            0
    END AS SHORTBOTTOMWEARMAN
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);







--여성 --
-- 상의
SELECT
  SUM(PERSON_TOPWEARLONGFEMALE + PERSON_TOPWEARSHORTFEMALE) AS TOPWEARFEMAN
 FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
  PERSON_TOPWEARLONGFEMALE
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
  PERSON_TOPWEARSHORTFEMALE
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);



-- 긴 상의를 입은 여성 비율
SELECT
    CASE
        WHEN SUM(PERSON_TOPWEARLONGFEMALE + PERSON_TOPWEARSHORTFEMALE) > 0 THEN
            (SUM(CASE WHEN PERSON_TOPWEARLONGFEMALE > 0 
                THEN PERSON_TOPWEARLONGFEMALE ELSE 0 END) * 100.0 /
                SUM(PERSON_TOPWEARLONGFEMALE + PERSON_TOPWEARSHORTFEMALE))
        ELSE
            0
    END AS LONGTOPWEARMAN
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

-- 짧은 상의를 입은 여성 비율
SELECT
    CASE
        WHEN SUM(PERSON_TOPWEARLONGFEMALE + PERSON_TOPWEARSHORTFEMALE) > 0 THEN
            (SUM(CASE WHEN PERSON_TOPWEARSHORTFEMALE > 0 
                THEN PERSON_TOPWEARSHORTFEMALE ELSE 0 END) * 100.0 /
                SUM(PERSON_TOPWEARLONGFEMALE + PERSON_TOPWEARSHORTFEMALE))
        ELSE
            0
    END AS SHORTTOPWEARFEMAN
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);




--하의
SELECT
  SUM(PERSON_BOTTOMWEARLONGFEMALE + PERSON_BOTTOMWEARSHORTFEMALE) AS TOPWEARMAN
 FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
  PERSON_BOTTOMWEARLONGFEMALE
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

SELECT
  PERSON_BOTTOMWEARSHORTFEMALE
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);

-- 긴 하의를 입은 여성
SELECT
    CASE
        WHEN SUM(PERSON_BOTTOMWEARLONGFEMALE + PERSON_BOTTOMWEARSHORTFEMALE) > 0 THEN
            (SUM(CASE WHEN PERSON_BOTTOMWEARLONGFEMALE > 0 
                THEN PERSON_BOTTOMWEARLONGFEMALE ELSE 0 END) * 100.0 /
                SUM(PERSON_BOTTOMWEARLONGFEMALE + PERSON_BOTTOMWEARSHORTFEMALE))
        ELSE
            0
    END AS LONGBOTTOMWEARFEMAN
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);


-- 짧은 상의를 입은 여성 비율
SELECT
    CASE
        WHEN SUM(PERSON_BOTTOMWEARLONGFEMALE + PERSON_BOTTOMWEARSHORTFEMALE) > 0 THEN
            (SUM(CASE WHEN PERSON_BOTTOMWEARSHORTFEMALE > 0 
                THEN PERSON_BOTTOMWEARSHORTFEMALE ELSE 0 END) * 100.0 /
                SUM(PERSON_BOTTOMWEARLONGFEMALE + PERSON_BOTTOMWEARSHORTFEMALE))
        ELSE
            0
    END AS SHORTBOTTOMWEARFEMAN
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = CONVERT(varchar, GETDATE(), 112);






--
SELECT
TOP 10
CNT.CAMERA_NAME   
, SUM(CNT.TOT_CNT)                       -- 카메라명
, SUM(CNT.PERSON)   AS personCount     -- 사람
, SUM(CNT.VEHICLE)  AS vehicleCount     -- 차량
, SUM(CNT.FACE)   AS faceCount             -- 얼굴
, SUM(CNT.LPR)    AS lprCount                -- 차량번호판
, SUM(CNT.INV_CNT)  AS invCntCount    -- 침입
, SUM(CNT.LOT_CNT)  AS lotCntCount    -- 배회
, SUM(CNT.CNT_CNT)  AS cntCntCount   -- 카운팅
, SUM(CNT.FAL_CNT)  AS falCntCont     -- 쓰러짐
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT CNT
WHERE SUBSTRING(CNT.OCCU_TIME, 1, 8) = '20231110'
GROUP BY CNT.CAMERA_NAME
ORDER BY SUM(CNT.TOT_CNT);

-- 사람
SELECT
CAMERA_NAME   
, PERSON   -- 사람
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = '20231110'
GROUP BY CAMERA_NAME
ORDER BY CNT.TOT_CNT;

SELECT
CNT.CAMERA_NAME   
, SUM(CNT.PERSON)   AS personCount     -- 사람
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT CNT
WHERE SUBSTRING(CNT.OCCU_TIME, 1, 8) = '20231110'
GROUP BY CNT.CAMERA_NAME
ORDER BY SUM(CNT.TOT_CNT);

-- 차량
SELECT
CNT.CAMERA_NAME   
, SUM(CNT.VEHICLE)  AS vehicleCount     -- 차량
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT CNT
WHERE SUBSTRING(CNT.OCCU_TIME, 1, 8) = '20231110'
GROUP BY CNT.CAMERA_NAME
ORDER BY SUM(CNT.TOT_CNT);

-- 얼굴
SELECT
CNT.CAMERA_NAME   
, SUM(CNT.FACE)   AS faceCount             -- 얼굴
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT CNT
WHERE SUBSTRING(CNT.OCCU_TIME, 1, 8) = '20231110'
GROUP BY CNT.CAMERA_NAME
ORDER BY SUM(CNT.TOT_CNT);

-- 차량번호판
SELECT
CNT.CAMERA_NAME   
, SUM(CNT.LPR)    AS lprCount                -- 차량번호판
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT CNT
WHERE SUBSTRING(CNT.OCCU_TIME, 1, 8) = '20231110'
GROUP BY CNT.CAMERA_NAME
ORDER BY SUM(CNT.TOT_CNT);

-- 침입
SELECT
CNT.CAMERA_NAME   
, SUM(CNT.INV_CNT)  AS invCntCount    -- 침입
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT CNT
WHERE SUBSTRING(CNT.OCCU_TIME, 1, 8) = '20231110'
GROUP BY CNT.CAMERA_NAME
ORDER BY SUM(CNT.TOT_CNT);

-- 배회
SELECT
CNT.CAMERA_NAME   
, SUM(CNT.LOT_CNT)  AS lotCntCount    -- 배회
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT CNT
WHERE SUBSTRING(CNT.OCCU_TIME, 1, 8) = '20231110'
GROUP BY CNT.CAMERA_NAME
ORDER BY SUM(CNT.TOT_CNT);

-- 카운팅
SELECT
CNT.CAMERA_NAME   
, SUM(CNT.CNT_CNT)  AS cntCntCount   -- 카운팅
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT CNT
WHERE SUBSTRING(CNT.OCCU_TIME, 1, 8) = '20231110'
GROUP BY CNT.CAMERA_NAME
ORDER BY SUM(CNT.TOT_CNT);




-- 차량 --

SELECT VEHICLE
 FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = '20231110';
CONVERT(varchar, GETDATE(), 112);

-- 자동차
SELECT VEHICLE_CAR
 FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = '20231110';
-- 버스
SELECT VEHICLE_BUS
 FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = '20231110';
-- 트럭
SELECT VEHICLE_TRUCK
 FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = '20231110';

-- 자동차 비율
SELECT
    CASE
        WHEN SUM(VEHICLE_CAR + VEHICLE_BUS + VEHICLE_TRUCK) > 0 THEN
            (SUM(CASE WHEN VEHICLE_CAR > 0 
                THEN VEHICLE_CAR ELSE 0 END) * 100.0 /
                SUM(VEHICLE_CAR + VEHICLE_BUS + VEHICLE_TRUCK))
        ELSE
            0
     END AS carPer
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE =  '20231110';

-- 버스 비율
SELECT
    CASE
        WHEN SUM(VEHICLE_CAR + VEHICLE_BUS + VEHICLE_TRUCK) > 0 THEN
            (SUM(CASE WHEN VEHICLE_BUS > 0 
                THEN VEHICLE_BUS ELSE 0 END) * 100.0 /
                SUM(VEHICLE_CAR + VEHICLE_BUS + VEHICLE_TRUCK))
        ELSE
            0
     END AS busPer
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE =  '20231110';

-- 트럭 비율
SELECT
    CASE
        WHEN SUM(VEHICLE_CAR + VEHICLE_BUS + VEHICLE_TRUCK) > 0 THEN
            (SUM(CASE WHEN VEHICLE_TRUCK > 0 
                THEN VEHICLE_TRUCK ELSE 0 END) * 100.0 /
                SUM(VEHICLE_CAR + VEHICLE_BUS + VEHICLE_TRUCK))
        ELSE
            0
     END AS truckPer
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE =  '20231110';


-- 이륜차

-- 오토바이
SELECT VEHICLE_MOTORCYCLE
 FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = '20231110';
-- 자전거
SELECT VEHICLE_BICYCLE
 FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = '20231110';



-- 오토바이 비율
SELECT
    CASE
        WHEN SUM(VEHICLE_MOTORCYCLE + VEHICLE_BICYCLE) > 0 THEN
            (SUM(CASE WHEN VEHICLE_MOTORCYCLE > 0 
                THEN VEHICLE_MOTORCYCLE ELSE 0 END) * 100.0 /
                SUM(VEHICLE_MOTORCYCLE + VEHICLE_BICYCLE))
        ELSE
            0
     END AS motorcyclePer
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE =  '20231110';

-- 자전거 비율
SELECT
    CASE
        WHEN SUM(VEHICLE_MOTORCYCLE + VEHICLE_BICYCLE) > 0 THEN
            (SUM(CASE WHEN VEHICLE_BICYCLE > 0 
                THEN VEHICLE_BICYCLE ELSE 0 END) * 100.0 /
                SUM(VEHICLE_MOTORCYCLE + VEHICLE_BICYCLE))
        ELSE
            0
     END AS cyclePer
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE =  '20231110';






SELECT FACE
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE =  '20231110';


SELECT FACE_MALE
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE =  '20231110';

SELECT FACE_FEMALE
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE =  '20231110';


--남자 얼굴 비율
SELECT
    CASE
        WHEN SUM(FACE) > 0 THEN
            (SUM(CASE WHEN FACE_MALE > 0 
                THEN FACE_MALE ELSE 0 END) * 100.0 /
                SUM(FACE))
        ELSE
            0
     END AS maleFacePer
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE =  '20231110';


--여자 얼굴 비율
SELECT
    CASE
        WHEN SUM(FACE) > 0 THEN
            (SUM(CASE WHEN FACE_FEMALE > 0 
                THEN FACE_FEMALE ELSE 0 END) * 100.0 /
                SUM(FACE))
        ELSE
            0
     END AS femaleFacePer
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE =  '20231110';


--남여 얼굴 수
SELECT
    FACE_FEMALE, FACE_MALE
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = '20231110';
CONVERT(varchar, GETDATE(), 112)


-- 얼굴페이지 악세사리 막대&라인 혼합차트 
SELECT
    FACE_HATMALE, FACE_HATFEMALE, FACE_GLASSESMALE, FACE_GLASSESFEMALE, FACE_MASKMALE, FACE_MASKFEMALE
FROM TB_AI_NVR_DASH_BOARD_DAILY_COUNT_SUMMARY
WHERE OCCU_DATE = '20231110';









































